import {
    Calculate as CalculateIcon, PersonOutline as PersonalDetailsIcon, MonetizationOn as FinancialDetailsIcon, 
    AppRegistration as RegistrationDetailsIcon, /*Add*/AddBusiness as AddPropertyIcon, PrivacyTip as TermsOfUseIcon, Accessibility as AccessibilityStatementIcon, Accessible as AccessibilitIcon,
    Payments as ProgramIcon, WavingHand as WelcomeIcon, Email as ContactUsIcon, Share as ShareIcon, Logout as LogoutIcon, 
    Android as AndroidIcon, Language as WebIcon,
    WorkspacePremium as MedaltIcon, Rule as MissDataIcon,
    KeyboardArrowDown as ArrowDownIcon, KeyboardArrowUp as ArrowUpIcon, KeyboardDoubleArrowDown as DoubleArrowDownIcon, Done as OKIcon, Close as CancelIcon,
    CheckCircle as SuccessIcon, Error as ErrorIcon, Warning as WarningIcon, Message as MessageIcon, Lightbulb as TooltipIcon, Close as CloseIcon,  
    Menu as MenuIcon, MoreVert as MoreIcon, Delete as DeleteIcon, Edit as EditIcon, ArrowBackIos as BackIcon,
    ZoomOutMap as ZoomOutIcon, ZoomInMap as ZoomInIcon, HighlightOff as ClosePropertyMenuIcon, Help as HelpIcon, RestartAlt as RestartIcon,
    PriorityHigh as AttentionIcon,
    Visibility as ShowPasswordIcon,
    VisibilityOff as HidePasswordIcon,
    Redo as  RollbackIcons,
    ArrowCircleLeftOutlined as ScrollArrowLeftIcon, ArrowCircleRightOutlined as ScrollArrowRightIcon, 
    ViewWeekRounded as ViewComfyIcon, ViewSidebarRounded as ViewCompactIcon, 
    AccountCircle as MissingAvatarIcon,
    AddCircle as AddMediatIcon,
    AddCircle as AddAdditionalFundingSourceIcon,
    Slideshow as MovieIcon,
    Photo as PictureIcon,
    VolumeOff as MuteIcon,
    VolumeUp as SoundIcon
} from '@mui/icons-material'


export {
    CalculateIcon,
    PersonalDetailsIcon,
    FinancialDetailsIcon,
    RegistrationDetailsIcon,
    AddPropertyIcon,
    TermsOfUseIcon,
    AccessibilityStatementIcon,
    AccessibilitIcon,
    ProgramIcon,
    WelcomeIcon,
    ContactUsIcon,
    ShareIcon,
    LogoutIcon,
    AndroidIcon,
    WebIcon,
    MedaltIcon,
    MissDataIcon,
    ArrowDownIcon,
    ArrowUpIcon,
    DoubleArrowDownIcon,
    OKIcon,
    CancelIcon,
    RollbackIcons,
    ScrollArrowLeftIcon,
    ScrollArrowRightIcon,
    ViewComfyIcon,
    ViewCompactIcon,
    AttentionIcon,
    ZoomOutIcon,
    ZoomInIcon,
    ClosePropertyMenuIcon,
    HelpIcon,
    RestartIcon,
    ShowPasswordIcon,
    HidePasswordIcon,
    MissingAvatarIcon, 
    SuccessIcon,
    ErrorIcon,
    WarningIcon,
    MessageIcon,
    TooltipIcon,
    CloseIcon,
    MenuIcon,
    MoreIcon,
    DeleteIcon,
    EditIcon,
    BackIcon,
    AddMediatIcon,
    AddAdditionalFundingSourceIcon,
    MovieIcon,
    PictureIcon,
    MuteIcon,
    SoundIcon
}

export const IconSizes = { 
    Small: { fontSize: 20 },
    Medium: { fontSize: 25 },
    Large: { fontSize: 30 },
}
